# -*- coding: utf-8 -*-
"""ProyectoF.inal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPNd8YGX88tzBpOdZruPcVF9KTcOp7e5
"""

import pandas as pd
import random
import os
from datetime import datetime
import math

porcentajes_semestre = [14, 13, 12, 11, 10, 10, 9, 8, 7, 6]
cupos_semestre = [30, 30, 30, 25, 25, 25, 20, 20, 20, 10]
horas_trabajadas = [96, 64, 32, 16]
horas_independientes = [120, 80, 64, 32]

datos = pd.read_csv('NombresArgentina.csv', encoding='ISO-8859-1', nrows=10000)
nombres = []

for indice_fila, fila in datos.iterrows():
  for nombre_columna, valor in fila.items():
    if nombre_columna == 'name':
      nombres.append(valor)

datos = pd.read_csv('ApellidosArgentina.csv', encoding='ISO-8859-1', nrows=10000)
apellidos = []

for indice_fila, fila in datos.iterrows():
  for nombre_columna, valor in fila.items():
    if nombre_columna == 'lastname':
      apellidos.append(valor)

numeros_aleatorios = [random.randint(0, 9999) for _ in range(1000)]
nombres_finales = []
for a in numeros_aleatorios:
  nombres_finales.append(nombres[a])

numeros_aleatorios = [random.randint(0, 9999) for _ in range(1000)]
apellidos_finales = []
for a in numeros_aleatorios:
  apellidos_finales.append(apellidos[a])

nombres_apellidos = []
for a in range(len(nombres_finales)):
  nombres_apellidos.append((nombres_finales[a].capitalize() + ' ' +  apellidos_finales[a].capitalize()))

